Better multiple related resources request example
json-api/json-api pull request #1227
Opened 2017-10-14 05:23 UTC by bf4

> GET /articles/1?include=author,comments.author

is confusing since `author` and `comments.author` both reference the `author` resource', 
but with different meaning.

It looks a lot like

GET /users/1?include=articles,articles.comments

which is identical to

GET /users/1?include=articles.comments

since full linkage requires intermediate resources to be returned

So, I've changed the the related resources to be more obviously different

2017-10-14 05:24 UTC, bf4 commented on _format/1.0/index.md
> +GET /articles/1?include=ratings,comments.author HTTP/1.1
or maybe `author,comments.rating` ¯\_(ツ)_/¯

2017-10-14 05:26 UTC, bf4 commented on _format/1.0/index.md
> +GET /articles/1?include=ratings,comments.author HTTP/1.1
It might also be worth noting that the included resources are names by their relationship names, not by their resource types

2022-02-13 15:37 UTC, jelhan requested changes
Thanks a lot for this proposal. I agree that having `author` twice could be confusing. Additionally I would switch the order. Than it would directly add to the examples given before. In order they would be the following:

```
GET /articles/1?include=comments HTTP/1.1
GET /articles/1?include=comments.author HTTP/1.1
GET /articles/1?include=comments.author,ratings HTTP/1.1
```

2022-02-13 15:37 UTC, jelhan commented on _format/1.0/index.md
> +GET /articles/1?include=ratings,comments.author HTTP/1.1
Do you mind switching the order? I think it is easier if the new part (compared to the previous examples) is added at the end.

```suggestion
GET /articles/1?include=comments.author,ratings HTTP/1.1
```

2022-06-10 20:32 UTC, dgeb approved these changes
Thanks @bf4 and @jelhan. I can see how this is subtly more clear.

2022-06-10 20:32 UTC, merged

2022-06-10 20:34 UTC, dgeb commented
@bf4 / @jelhan would either of you be up for applying this same change to the 1.1 spec in another PR?

2022-06-13 16:41 UTC, jelhan commented
> @bf4 / @jelhan would either of you be up for applying this same change to the 1.1 spec in another PR?

Done in  #1629.