cleanup(profiles): special case default handling of unrecognized query param vals
json-api/json-api pull request #1306
Opened 2018-10-16 16:09 UTC by ethanresnick

Before, if a profile was applied with a query parameter that had an unrecognized value, the profile was ignored by default. This makes the default to fail with a 400 Bad Request instead. I think this better reflects the semantics that, when using query parameters, the client is trying to force the server to apply the profile, or fail the request.

2018-10-20 18:17 UTC, ethanresnick commented
@wimleers Wanted to make sure you saw this

2018-11-03 20:02 UTC, dgeb commented on _format/1.1/index.md
> +     parameter, the server **MUST** fail the request and respond with a
> If the unrecognized value occurs is the value of a profile-defined query parameter,

This phrasing seems a bit off - "occurs is" seems like a typo. 

Perhaps this is clearer: "If the value of a profile-defined query parameter is unrecognized,"

2018-11-03 20:05 UTC, dgeb commented on _format/1.1/index.md
> +  2. Otherwise, if the unrecognized value is a JSON object, and the only thing
I think this should clarify that it applies to a JSON object _in a document_.

2018-11-03 20:06 UTC, dgeb requested changes
@ethanresnick Just needs some minor tweaks to improve clarity - looks good overall.

2018-11-03 23:09 UTC, ethanresnick commented
@dgeb Ok, I've applied your suggestions. Take a look!

2018-11-04 21:48 UTC, dgeb approved these changes
@ethanresnick looks good now - thanks!

2018-11-04 21:48 UTC, merged