only client-requested sparse fieldsets are exception to full linkage requirement
json-api/json-api pull request #1615
Opened 2022-02-21 11:33 UTC by jelhan

The current wording could be misunderstood that also fields excluded by the server if client does _not_ request a sparse fieldset are an exception for full linkage requirement. This changes clarifies that only exception is if a client _explicilty_ requested a sparse fieldset, which does not include a relationship required for full linkage.

Closes #1614

2022-02-21 20:23 UTC, bradjones1 commented
I think this does address the question I had in #1614. I might recommend using "specified by" instead of "requested by" the client, or even "specified in the client request"? But I think it's OK as written, too, if you have a strong feeling about it.

2022-02-23 10:14 UTC, jelhan commented
> I might recommend using "specified by" instead of "requested by" the client, or even "specified in the client request"? But I think it's OK as written, too, if you have a strong feeling about it.

I don't have strong feelings about. Personally I feel it could be confusing to use the term "specify" in a specification for something else than the specification itself.

But I'm not a native speaker. Will leave this one for editors to decide.

2022-02-23 12:38 UTC, dgeb commented
I think this wording is fine. The important clarification here is that the client is in control of the request.

2022-02-23 12:39 UTC, merged

2022-02-23 12:58 UTC, auvipy commented
can we expect a RC 4 soon? it's been 16 months a lot of PR merged in the mean time

2022-03-30 13:35 UTC, jonatanlr98 reviewed
links": { "self": "http://example.com/posts" }

2022-03-30 13:36 UTC, jonatanlr98 commented
links": { "self": "http://example.com/posts" }

2022-03-30 13:39 UTC, jonatanlr98 requested changes
links": { "related": { "href": "http://example.com/articles/1/comments", "meta": { "count": 10 } } }

2022-03-30 18:28 UTC, bradjones1 commented
@jonatanlr98 This is merged and your comments are without context. Open a new issue or PR if you have issues with this.